name: Manual workflow

on:
  schedule:
  - cron: '25 16 * * *'
  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
    - name: Send Notifications
      env:
        KEY: ${{ secrets.KEY }} 
      run: |
        curl -X POST "https://notifications.clearwind.ca/rss/parse/0d72687a-b7fd-4b84-84f9-d09b5b20bd33" -F "key=$KEY" > out.txt
        cat out.txt
