name: Manual workflow

on:
  schedule:
  - cron: '25 16 * * *'
  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
    - name: Send Notifications
      env:
        KEY: ${{ secrets.KEY }} 
      run: |
        wget "https://notifications.clearwind.ca/" > out.txt
        cat out.txt
