name: Manual workflow

on:
  schedule:
  - cron: '25 16 * * *'
  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: |
        curl -X POST "https://notifications.clearwind.ca/rss/parse/98b1439e-fbd5-4599-8cdd-719ff54df707" -F 'key='
